class WeatherModel {
  String regionNAme;
  DateTime lastUpdate;
  DateTime dateFirst;
  DateTime dateSecond;
  DateTime dateThird;
  double tempAvgDayFirst;
  double tempAvgDayThird;
  double tempAvgDaySecond;
  double tempCurrent;
  int cloudCurrent;
  double maxTempThirdDay;
  double maxTempFirstDay;
  double maxTempSecondDay;
  double minTempThirdDay;
  double minTempSecondDay;
  double minTempFirstDay;
  String weatherStateNameFirst;
  String weatherStateNameSecond;
  String weatherStateNameThird;
  String weatherStateNameCurrent;
  double feelslike;
  double windspeedDayFirst;
  double windspeedDaySecond;
  double windspeedDayThird;
  double windspeedCurrent;
  double pressure;
  int humidityCurrent;
  int avgHumidityFirst;
  int avgHumiditySecond;
  int avgHumidityThird;
  String windDir;
  String sunriseFirst;
  String sunriseSecond;
  String sunriseThird;
  String sunsetFirst;
  String sunsetSecond;
  String sunsetThird;
  String moonriseFirst;
  String moonriseSecond;
  String moonriseThird;
  int chanceRainFirst;
  int chanceRainSecond;
  int chanceRainThird;
  String iconFirstDay;
  String iconSecondDay;
  String iconThirdDay;
  DateTime timeHourOne;
  DateTime timeHourTwo;
  DateTime timeHourThree;
  DateTime timeHourFour;
  DateTime timeHourFive;
  DateTime timeHourSix;
  DateTime timeHourSeven;
  DateTime timeHourEight;
  DateTime timeHourNine;
  DateTime timeHourTen;
  DateTime timeHourEleven;
  DateTime timeHourTweleve;
  DateTime timeHourThirteen;
  DateTime timeHourFourteen;
  DateTime timeHourFifteen;
  DateTime timeHourSixteen;
  DateTime timeHourSeventeen;
  DateTime timeHourEighteen;
  DateTime timeHourNineteen;
  DateTime timeHourTwenty;
  DateTime timeHourTwentyone;
  DateTime timeHourTwentytwo;
  DateTime timeHourTwentythree;
  DateTime timeHourTwentyfour;
  String iconHourOne;
  String iconHourTwo;
  String iconHourThree;
  String iconHourFour;
  String iconHourFive;
  String iconHourSix;
  String iconHourSeven;
  String iconHourEight;
  String iconHourNine;
  String iconHourTen;
  String iconHourEleven;
  String iconHourTweleve;
  String iconHourThirteen;
  String iconHourFourteen;
  String iconHourFifteen;
  String iconHourSixteen;
  String iconHourSeventeen;
  String iconHourEighteen;
  String iconHourNineteen;
  String iconHourTwenty;
  String iconHourTwentyone;
  String iconHourTwentytwo;
  String iconHourTwentythree;
  String iconHourTwentyfour;
  double tempHourOne;
  double tempHourTwo;
  double tempHourThree;
  double tempHourFour;
  double tempHourFive;
  double tempHourSix;
  double tempHourSeven;
  double tempHourEight;
  double tempHourNine;
  double tempHourTen;
  double tempHourEleven;
  double tempHourTweleve;
  double tempHourThirteen;
  double tempHourFourteen;
  double tempHourFifteen;
  double tempHourSixteen;
  double tempHourSeventeen;
  double tempHourEighteen;
  double tempHourNineteen;
  double tempHourTwenty;
  double tempHourTwentyone;
  double tempHourTwentytwo;
  double tempHourTwentythree;
  double tempHourTwentyfour;
  double windHourOne;
  double windHourTwo;
  double windHourThree;
  double windHourFour;
  double windHourFive;
  double windHourSix;
  double windHourSeven;
  double windHourEight;
  double windHourNine;
  double windHourTen;
  double windHourEleven;
  double windHourTweleve;
  double windHourThirteen;
  double windHourFourteen;
  double windHourFifteen;
  double windHourSixteen;
  double windHourSeventeen;
  double windHourEighteen;
  double windHourNineteen;
  double windHourTwenty;
  double windHourTwentyone;
  double windHourTwentytwo;
  double windHourTwentythree;
  double windHourTwentyfour;
  double airQualityCO;
  double airQualityNO2;
  double airQualityO3;
  double airQualitySO2;
  double airQualityPM2_5;
  double airQualityPM10;
  int airQuality;
  dynamic error;

  WeatherModel({
    this.error,
    required this.regionNAme,
    required this.lastUpdate,
    required this.dateFirst,
    required this.dateSecond,
    required this.dateThird,
    required this.tempCurrent,
    required this.tempAvgDayFirst,
    required this.tempAvgDaySecond,
    required this.tempAvgDayThird,
    required this.maxTempThirdDay,
    required this.minTempThirdDay,
    required this.minTempFirstDay,
    required this.maxTempFirstDay,
    required this.maxTempSecondDay,
    required this.minTempSecondDay,
    required this.weatherStateNameCurrent,
    required this.feelslike,
    required this.windspeedDayFirst,
    required this.windspeedDaySecond,
    required this.windspeedDayThird,
    required this.pressure,
    required this.humidityCurrent,
    required this.windDir,
    required this.sunriseFirst,
    required this.sunriseSecond,
    required this.sunriseThird,
    required this.sunsetFirst,
    required this.sunsetSecond,
    required this.sunsetThird,
    required this.moonriseFirst,
    required this.moonriseSecond,
    required this.moonriseThird,
    required this.chanceRainFirst,
    required this.chanceRainSecond,
    required this.chanceRainThird,
    required this.iconFirstDay,
    required this.iconSecondDay,
    required this.iconThirdDay,
    required this.weatherStateNameFirst,
    required this.weatherStateNameSecond,
    required this.weatherStateNameThird,
    required this.windspeedCurrent,
    required this.avgHumidityFirst,
    required this.avgHumiditySecond,
    required this.avgHumidityThird,
    required this.windHourOne,
    required this.windHourTwo,
    required this.windHourThree,
    required this.windHourFour,
    required this.windHourFive,
    required this.windHourSix,
    required this.windHourSeven,
    required this.windHourEight,
    required this.windHourNine,
    required this.windHourTen,
    required this.windHourEleven,
    required this.windHourTweleve,
    required this.windHourThirteen,
    required this.windHourFourteen,
    required this.windHourFifteen,
    required this.windHourSixteen,
    required this.windHourSeventeen,
    required this.windHourEighteen,
    required this.windHourNineteen,
    required this.windHourTwenty,
    required this.windHourTwentyone,
    required this.windHourTwentytwo,
    required this.windHourTwentythree,
    required this.windHourTwentyfour,
    required this.tempHourOne,
    required this.tempHourTwo,
    required this.tempHourThree,
    required this.tempHourFour,
    required this.tempHourFive,
    required this.tempHourSix,
    required this.tempHourSeven,
    required this.tempHourEight,
    required this.tempHourNine,
    required this.tempHourTen,
    required this.tempHourEleven,
    required this.tempHourTweleve,
    required this.tempHourThirteen,
    required this.tempHourFourteen,
    required this.tempHourFifteen,
    required this.tempHourSixteen,
    required this.tempHourSeventeen,
    required this.tempHourEighteen,
    required this.tempHourNineteen,
    required this.tempHourTwenty,
    required this.tempHourTwentyone,
    required this.tempHourTwentytwo,
    required this.tempHourTwentythree,
    required this.tempHourTwentyfour,
    required this.iconHourOne,
    required this.iconHourTwo,
    required this.iconHourThree,
    required this.iconHourFour,
    required this.iconHourFive,
    required this.iconHourSix,
    required this.iconHourSeven,
    required this.iconHourEight,
    required this.iconHourNine,
    required this.iconHourTen,
    required this.iconHourEleven,
    required this.iconHourTweleve,
    required this.iconHourThirteen,
    required this.iconHourFourteen,
    required this.iconHourFifteen,
    required this.iconHourSixteen,
    required this.iconHourSeventeen,
    required this.iconHourEighteen,
    required this.iconHourNineteen,
    required this.iconHourTwenty,
    required this.iconHourTwentyone,
    required this.iconHourTwentytwo,
    required this.iconHourTwentythree,
    required this.iconHourTwentyfour,
    required this.timeHourOne,
    required this.timeHourTwo,
    required this.timeHourThree,
    required this.timeHourFour,
    required this.timeHourFive,
    required this.timeHourSix,
    required this.timeHourSeven,
    required this.timeHourEight,
    required this.timeHourNine,
    required this.timeHourTen,
    required this.timeHourEleven,
    required this.timeHourTweleve,
    required this.timeHourThirteen,
    required this.timeHourFourteen,
    required this.timeHourFifteen,
    required this.timeHourSixteen,
    required this.timeHourSeventeen,
    required this.timeHourEighteen,
    required this.timeHourNineteen,
    required this.timeHourTwenty,
    required this.timeHourTwentyone,
    required this.timeHourTwentytwo,
    required this.timeHourTwentythree,
    required this.timeHourTwentyfour,
    required this.cloudCurrent,
    required this.airQuality,
    required this.airQualityCO,
    required this.airQualityNO2,
    required this.airQualityO3,
    required this.airQualitySO2,
    required this.airQualityPM2_5,
    required this.airQualityPM10,
  });

  factory WeatherModel.fromJson(data) {
    var forecastDayFirst = data['forecast']['forecastday'][0]['day'];
    var forecastAstroDayFirst = data['forecast']['forecastday'][0]['astro'];
    var forcastDaySecond = data['forecast']['forecastday'][1]['day'];
    var forecastAstroDaySecond = data['forecast']['forecastday'][1]['astro'];
    var forcastDayThird = data['forecast']['forecastday'][2]['day'];
    var forecastAstroDayThird = data['forecast']['forecastday'][2]['astro'];
    var dateFirst = data['forecast']['forecastday'][0]['date'];
    var dateSecond = data['forecast']['forecastday'][1]['date'];
    var dateThird = data['forecast']['forecastday'][2]['date'];
    var hour = data['forecast']['forecastday'][0]['hour'];

    var current = data['current'];
    return WeatherModel(
      regionNAme: data['location']['region'],
      lastUpdate: DateTime.parse(current['last_updated']),
      dateFirst: DateTime.parse(dateFirst),
      dateSecond: DateTime.parse(dateSecond),
      dateThird: DateTime.parse(dateThird),
      tempCurrent: current['temp_c'],
      cloudCurrent: current['cloud'],
      airQualityCO: current['air_quality']['co'],
      airQualityO3: current['air_quality']['o3'],
      airQualityNO2: current['air_quality']['no2'],
      airQualitySO2: current['air_quality']['so2'],
      airQualityPM2_5: current['air_quality']['pm2_5'],
      airQualityPM10: current['air_quality']['pm10'],
      airQuality: current['air_quality']['us-epa-index'],
      tempAvgDayFirst: forecastDayFirst['avgtemp_c'],
      tempAvgDaySecond: forcastDaySecond['avgtemp_c'],
      tempAvgDayThird: forcastDayThird['avgtemp_c'],
      maxTempFirstDay: forecastDayFirst['maxtemp_c'],
      minTempFirstDay: forecastDayFirst['mintemp_c'],
      maxTempSecondDay: forcastDaySecond['maxtemp_c'],
      minTempSecondDay: forcastDaySecond['mintemp_c'],
      maxTempThirdDay: forcastDayThird['maxtemp_c'],
      minTempThirdDay: forcastDayThird['mintemp_c'],
      weatherStateNameCurrent: current['condition']['text'],
      weatherStateNameFirst: forecastDayFirst['condition']['text'],
      weatherStateNameSecond: forcastDaySecond['condition']['text'],
      weatherStateNameThird: forcastDayThird['condition']['text'],
      feelslike: current['feelslike_c'],
      windspeedCurrent: current['wind_kph'],
      windspeedDayFirst: forecastDayFirst['maxwind_kph'],
      windspeedDaySecond: forcastDaySecond['maxwind_kph'],
      windspeedDayThird: forcastDayThird['maxwind_kph'],
      pressure: current['pressure_mb'],
      humidityCurrent: current['humidity'],
      avgHumidityFirst: forecastDayFirst['avghumidity'],
      avgHumiditySecond: forcastDaySecond['avghumidity'],
      avgHumidityThird: forcastDayThird['avghumidity'],
      windDir: current['wind_dir'],
      sunriseFirst: forecastAstroDayFirst['sunrise'],
      sunriseSecond: forecastAstroDaySecond['sunrise'],
      sunriseThird: forecastAstroDayThird['sunrise'],
      sunsetFirst: forecastAstroDayFirst['sunset'],
      sunsetSecond: forecastAstroDaySecond['sunset'],
      sunsetThird: forecastAstroDayThird['sunset'],
      moonriseFirst: forecastAstroDayFirst['moonrise'],
      moonriseSecond: forecastAstroDaySecond['moonrise'],
      moonriseThird: forecastAstroDayThird['moonrise'],
      chanceRainFirst: forecastDayFirst['daily_chance_of_rain'],
      chanceRainSecond: forcastDaySecond['daily_chance_of_rain'],
      chanceRainThird: forcastDayThird['daily_chance_of_rain'],
      iconFirstDay: forecastDayFirst['condition']['icon'],
      iconSecondDay: forcastDaySecond['condition']['icon'],
      iconThirdDay: forcastDayThird['condition']['icon'],
      timeHourOne: DateTime.parse(hour[0]['time']),
      timeHourTwo: DateTime.parse(hour[1]['time']),
      timeHourThree: DateTime.parse(hour[2]['time']),
      timeHourFour: DateTime.parse(hour[3]['time']),
      timeHourFive: DateTime.parse(hour[4]['time']),
      timeHourSix: DateTime.parse(hour[5]['time']),
      timeHourSeven: DateTime.parse(hour[6]['time']),
      timeHourEight: DateTime.parse(hour[7]['time']),
      timeHourNine: DateTime.parse(hour[8]['time']),
      timeHourTen: DateTime.parse(hour[9]['time']),
      timeHourEleven: DateTime.parse(hour[10]['time']),
      timeHourTweleve: DateTime.parse(hour[11]['time']),
      timeHourThirteen: DateTime.parse(hour[12]['time']),
      timeHourFourteen: DateTime.parse(hour[13]['time']),
      timeHourFifteen: DateTime.parse(hour[14]['time']),
      timeHourSixteen: DateTime.parse(hour[15]['time']),
      timeHourSeventeen: DateTime.parse(hour[16]['time']),
      timeHourEighteen: DateTime.parse(hour[17]['time']),
      timeHourNineteen: DateTime.parse(hour[18]['time']),
      timeHourTwenty: DateTime.parse(hour[19]['time']),
      timeHourTwentyone: DateTime.parse(hour[20]['time']),
      timeHourTwentytwo: DateTime.parse(hour[21]['time']),
      timeHourTwentythree: DateTime.parse(hour[22]['time']),
      timeHourTwentyfour: DateTime.parse(hour[23]['time']),
      tempHourOne: hour[0]['temp_c'],
      tempHourTwo: hour[1]['temp_c'],
      tempHourThree: hour[2]['temp_c'],
      tempHourFour: hour[3]['temp_c'],
      tempHourFive: hour[4]['temp_c'],
      tempHourSix: hour[5]['temp_c'],
      tempHourSeven: hour[6]['temp_c'],
      tempHourEight: hour[7]['temp_c'],
      tempHourNine: hour[8]['temp_c'],
      tempHourTen: hour[9]['temp_c'],
      tempHourEleven: hour[10]['temp_c'],
      tempHourTweleve: hour[11]['temp_c'],
      tempHourThirteen: hour[12]['temp_c'],
      tempHourFourteen: hour[13]['temp_c'],
      tempHourFifteen: hour[14]['temp_c'],
      tempHourSixteen: hour[15]['temp_c'],
      tempHourSeventeen: hour[16]['temp_c'],
      tempHourEighteen: hour[17]['temp_c'],
      tempHourNineteen: hour[18]['temp_c'],
      tempHourTwenty: hour[19]['temp_c'],
      tempHourTwentyone: hour[20]['temp_c'],
      tempHourTwentytwo: hour[21]['temp_c'],
      tempHourTwentythree: hour[22]['temp_c'],
      tempHourTwentyfour: hour[23]['temp_c'],
      iconHourOne: hour[0]['condition']['icon'],
      iconHourTwo: hour[1]['condition']['icon'],
      iconHourThree: hour[2]['condition']['icon'],
      iconHourFour: hour[3]['condition']['icon'],
      iconHourFive: hour[4]['condition']['icon'],
      iconHourSix: hour[5]['condition']['icon'],
      iconHourSeven: hour[6]['condition']['icon'],
      iconHourEight: hour[7]['condition']['icon'],
      iconHourNine: hour[8]['condition']['icon'],
      iconHourTen: hour[9]['condition']['icon'],
      iconHourEleven: hour[10]['condition']['icon'],
      iconHourTweleve: hour[11]['condition']['icon'],
      iconHourThirteen: hour[12]['condition']['icon'],
      iconHourFourteen: hour[13]['condition']['icon'],
      iconHourFifteen: hour[14]['condition']['icon'],
      iconHourSixteen: hour[15]['condition']['icon'],
      iconHourSeventeen: hour[16]['condition']['icon'],
      iconHourEighteen: hour[17]['condition']['icon'],
      iconHourNineteen: hour[18]['condition']['icon'],
      iconHourTwenty: hour[19]['condition']['icon'],
      iconHourTwentyone: hour[20]['condition']['icon'],
      iconHourTwentytwo: hour[21]['condition']['icon'],
      iconHourTwentythree: hour[22]['condition']['icon'],
      iconHourTwentyfour: hour[23]['condition']['icon'],
      windHourOne: hour[0]['wind_kph'],
      windHourTwo: hour[1]['wind_kph'],
      windHourThree: hour[2]['wind_kph'],
      windHourFour: hour[3]['wind_kph'],
      windHourFive: hour[4]['wind_kph'],
      windHourSix: hour[5]['wind_kph'],
      windHourSeven: hour[6]['wind_kph'],
      windHourEight: hour[7]['wind_kph'],
      windHourNine: hour[8]['wind_kph'],
      windHourTen: hour[9]['wind_kph'],
      windHourEleven: hour[10]['wind_kph'],
      windHourTweleve: hour[11]['wind_kph'],
      windHourThirteen: hour[12]['wind_kph'],
      windHourFourteen: hour[13]['wind_kph'],
      windHourFifteen: hour[14]['wind_kph'],
      windHourSixteen: hour[15]['wind_kph'],
      windHourSeventeen: hour[16]['wind_kph'],
      windHourEighteen: hour[17]['wind_kph'],
      windHourNineteen: hour[18]['wind_kph'],
      windHourTwenty: hour[19]['wind_kph'],
      windHourTwentyone: hour[20]['wind_kph'],
      windHourTwentytwo: hour[21]['wind_kph'],
      windHourTwentythree: hour[22]['wind_kph'],
      windHourTwentyfour: hour[23]['wind_kph'],
    );
  }
}
